#import <Foundation/Foundation.h>
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
int main(int argc, const char * argv[]){
	@autoreleasepool{
		int array[2] = {0,1};
		int temp = 0;
		int total = 0;
		while (array[1] < 4000000){
				temp = array[0];
				array[0] = array[1] + array[0];
				array[1] = temp;	
				NSLog(@"%i %i",array[0],array[1]);
				if (array[0] % 2 == 0){
					total += array[0];
	
				}

		}	
		NSLog(@"%i ",total);
		return 0;
	}
}

